// Export a constant object named 'metadata' which contains metadata for the application.
// This export can be used to define page-level SEO information like the title and description.

// The 'metadata' object contains key-value pairs that provide information about the application.
export const metadata = {
  // 'title' is the name of the application, which will be used in the browser tab and for SEO purposes.
  title: "Create Next App",
  
  // 'description' provides a brief summary of the application, which is also helpful for SEO and social sharing.
  description: "Generated by create next app",
};
